# -*- coding: utf-8 -*-
"""Optimisation IA Aetherium

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m2KwktXeYWqNwEnCPaJsaoyXZVgPu7L3
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Aetherium Reservoir Computing - Hautes Performances
---------------------------------------------------
Optimisation du classifieur pour atteindre l'état de l'art du Reservoir Computing.
Utilise le Pooling spatial et un entraînement prolongé sur un large jeu de données.
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np
import time

# ==========================================
# 1. Le Cœur Fluide Aetherium
# ==========================================
class AetheriumCoreBatch(nn.Module):
    def __init__(self, N=64, L=2*np.pi, g=2.0, alpha=1.0, dt=0.01, device='cpu'):
        super().__init__()
        self.device = device
        self.N, self.L, self.g, self.alpha, self.dt = N, L, g, alpha, dt

        kx = torch.fft.fftfreq(N, d=L/N, device=self.device) * 2 * np.pi
        ky = torch.fft.fftfreq(N, d=L/N, device=self.device) * 2 * np.pi
        KX, KY = torch.meshgrid(kx, ky, indexing='ij')

        self.K2 = KX**2 + KY**2
        self.kinetic_op = torch.exp(-1j * (self.dt / 4.0) * self.K2)

    def solve_poisson(self, rho, rho0=1.0):
        rho_diff_hat = torch.fft.fftn(rho - rho0, dim=(-2, -1))
        V_hat = torch.zeros_like(rho_diff_hat)
        mask = self.K2 != 0
        V_hat[..., mask] = -self.alpha * rho_diff_hat[..., mask] / self.K2[mask]
        return torch.fft.ifftn(V_hat, dim=(-2, -1)).real

    def forward(self, psi):
        psi_hat = torch.fft.fftn(psi, dim=(-2, -1)) * self.kinetic_op
        psi = torch.fft.ifftn(psi_hat, dim=(-2, -1))

        rho = torch.abs(psi)**2
        V_eff = self.solve_poisson(rho) + self.g * rho
        psi = psi * torch.exp(-1j * self.dt * V_eff)

        psi_hat = torch.fft.fftn(psi, dim=(-2, -1)) * self.kinetic_op
        psi = torch.fft.ifftn(psi_hat, dim=(-2, -1))
        return psi

# ==========================================
# 2. La Couche de Lecture Optimisée
# ==========================================
class OptimizedReadout(nn.Module):
    def __init__(self, fluid_grid=64, pool_size=2, num_classes=10):
        super().__init__()
        # OPTIMISATION 1 : Average Pooling
        # Simule des capteurs physiques macroscopiques lisant le fluide
        self.pool = nn.AvgPool2d(kernel_size=pool_size)

        # Calcul de la nouvelle taille après pooling (ex: 64x64 -> 32x32)
        reduced_size = fluid_grid // pool_size
        flattened_size = reduced_size * reduced_size

        # Le réseau reste purement linéaire (c'est la règle d'or du Reservoir Computing)
        self.fc = nn.Linear(flattened_size, num_classes)

    def forward(self, rho_fluid):
        # rho_fluid est de dimension [Batch, 64, 64]
        x = rho_fluid.unsqueeze(1) # Ajoute la dimension 'canal' : [Batch, 1, 64, 64]
        x = self.pool(x)           # Réduit à [Batch, 1, 32, 32]
        x = x.view(x.size(0), -1)  # Aplatit à [Batch, 1024]
        return self.fc(x)

# ==========================================
# 3. Moteur d'Entraînement Hautes Performances
# ==========================================
def main():
    device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
    print(f"🚀 Lancement de l'Optimisation IA sur : {device}")

    # --- Paramètres ---
    N_grid = 64
    fluid_steps = 10     # Temps de réflexion du fluide
    g_phys = 2.0         # Pression Quantique
    alpha_phys = 1.0     # Gravité / Poisson
    epochs = 15          # Plus d'époques pour bien apprendre l'hologramme

    # --- Modèles ---
    aetherium = AetheriumCoreBatch(N=N_grid, g=g_phys, alpha=alpha_phys, device=device)
    readout = OptimizedReadout(fluid_grid=N_grid, pool_size=2).to(device)

    # Optimiseur robuste
    optimizer = optim.Adam(readout.parameters(), lr=0.005, weight_decay=1e-5)
    criterion = nn.CrossEntropyLoss()

    # --- Données (10 000 Train / 2 000 Test) ---
    transform = transforms.Compose([transforms.Resize((N_grid, N_grid)), transforms.ToTensor()])
    print("Chargement de la base de données MNIST...")
    train_set = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
    test_set = torchvision.datasets.MNIST(root='./data', train=False, download=True, transform=transform)

    train_loader = torch.utils.data.DataLoader(torch.utils.data.Subset(train_set, range(10000)), batch_size=256, shuffle=True)
    test_loader = torch.utils.data.DataLoader(torch.utils.data.Subset(test_set, range(2000)), batch_size=256, shuffle=False)

    # --- Boucle d'Entraînement ---
    history_acc = []
    print("\n[ DÉBUT DE L'ENTRAÎNEMENT DU READOUT (PHYSIQUE FIGÉE) ]")
    start_time = time.time()

    for epoch in range(epochs):
        readout.train()
        correct, total = 0, 0

        for images, labels in train_loader:
            images, labels = images.to(device).squeeze(1), labels.to(device)

            # ÉTAPE 1 : Le calcul physique (sans gradient)
            with torch.no_grad():
                theta_init = images * torch.pi * 2.0
                psi = torch.sqrt(torch.ones_like(theta_init)) * torch.exp(1j * theta_init)
                for _ in range(fluid_steps):
                    psi = aetherium(psi)
                fluid_density = torch.abs(psi)**2

            # ÉTAPE 2 : L'apprentissage de l'IA (Couche Linéaire)
            optimizer.zero_grad()
            outputs = readout(fluid_density)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            # Métriques
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

        acc = 100. * correct / total
        history_acc.append(acc)
        print(f"Epoch [{epoch+1}/{epochs}] | Précision Train : {acc:.2f}% | Temps : {time.time()-start_time:.1f}s")

    # --- Évaluation sur le Test Set ---
    print("\n[ ÉVALUATION FINALE SUR IMAGES INCONNUES ]")
    readout.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device).squeeze(1), labels.to(device)

            theta_init = images * torch.pi * 2.0
            psi = torch.sqrt(torch.ones_like(theta_init)) * torch.exp(1j * theta_init)
            for _ in range(fluid_steps):
                psi = aetherium(psi)
            fluid_density = torch.abs(psi)**2

            outputs = readout(fluid_density)
            correct += outputs.max(1)[1].eq(labels).sum().item()
            total += labels.size(0)

    final_acc = 100. * correct / total
    print(f">>> PRÉCISION FINALE (TEST) : {final_acc:.2f}% <<<")

    # --- Affichage de la courbe ---
    plt.figure(figsize=(8, 5))
    plt.plot(range(1, epochs+1), history_acc, marker='o', color='purple', linewidth=2, label="Aetherium Linear Readout")
    plt.axhline(y=final_acc, color='r', linestyle='--', label=f"Test Accuracy ({final_acc:.1f}%)")
    plt.title("Courbe d'apprentissage de l'IA Aetherium", fontsize=14)
    plt.xlabel("Époques d'entraînement")
    plt.ylabel("Précision (%)")
    plt.grid(True, linestyle=':', alpha=0.7)
    plt.legend()
    plt.savefig('aetherium_learning_curve.png', dpi=150)
    print("Graphique sauvegardé dans 'aetherium_learning_curve.png'")

if __name__ == "__main__":
    main()