# -*- coding: utf-8 -*-
"""AGI Aetherium Avancée (Multi-Tâches)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CuODLWj1M4L3ItVtinqBA4h6Ajge2OfP
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Aetherium AGI Avancée - Superposition de Souvenirs
--------------------------------------------------
Démonstration de la capacité d'un réseau de Hopfield continu (Fluide)
à stocker de multiples concepts simultanément dans la Gravité Latente (Phi)
et à résoudre les conflits topologiques lors du rappel.
"""

import torch
import torch.fft
import numpy as np
import matplotlib.pyplot as plt

class AetheriumAGI_Multi(torch.nn.Module):
    def __init__(self, N=128, L=20.0, g=1.5, alpha=4.0, nu_collatz=0.015, dt=0.05, device='cpu'):
        super().__init__()
        self.device = torch.device(device if torch.cuda.is_available() else 'cpu')
        self.N, self.L, self.g, self.alpha, self.nu, self.dt = N, L, g, alpha, nu_collatz, dt

        x = torch.linspace(-L/2, L/2, N, device=self.device)
        self.X, self.Y = torch.meshgrid(x, x, indexing='ij')

        kx = torch.fft.fftfreq(N, d=L/N, device=self.device) * 2 * np.pi
        ky = torch.fft.fftfreq(N, d=L/N, device=self.device) * 2 * np.pi
        KX, KY = torch.meshgrid(kx, ky, indexing='ij')
        self.K2 = KX**2 + KY**2
        self.kinetic_op = torch.exp(-1j * (self.dt / 4.0) * self.K2)
        self.kinetic_damp = torch.exp(-self.nu * self.dt * self.K2)

        # Inconscient Gravitationnel (La somme de TOUTES les mémoires)
        self.phi_memory = torch.zeros((N, N), dtype=torch.float32, device=self.device)

    def add_memory(self, psi_target):
        """Ajoute un nouveau souvenir par superposition gravitationnelle"""
        rho = torch.abs(psi_target)**2
        rho_diff_hat = torch.fft.fftn(rho - torch.mean(rho))
        V_hat = torch.zeros_like(rho_diff_hat)
        mask = self.K2 != 0
        V_hat[mask] = -self.alpha * rho_diff_hat[mask] / self.K2[mask]
        # ADDITION des topologies
        self.phi_memory += torch.fft.ifftn(V_hat).real

    def forward(self, psi):
        """Pensée fluide et reconstruction"""
        psi_hat = torch.fft.fftn(psi) * self.kinetic_op * self.kinetic_damp
        psi = torch.fft.ifftn(psi_hat)

        rho = torch.abs(psi)**2
        V_eff = self.g * rho + self.phi_memory

        evolution_phase = torch.exp(-1j * self.dt * V_eff)
        evolution_relaxation = torch.exp(-self.nu * self.dt * V_eff)

        psi = psi * evolution_phase * evolution_relaxation
        norm = torch.sqrt(torch.mean(torch.abs(psi)**2))
        psi = psi / norm

        psi_hat = torch.fft.fftn(psi) * self.kinetic_op * self.kinetic_damp
        psi = torch.fft.ifftn(psi_hat)
        return psi

# ==========================================
# Expérience : Discrimination de Mémoires
# ==========================================
if __name__ == "__main__":
    print("Démarrage de l'AGI Fluide Multi-Concepts...")
    N_grid = 128
    cerveau = AetheriumAGI_Multi(N=N_grid, L=20.0)

    R = torch.sqrt(cerveau.X**2 + cerveau.Y**2)

    # Concept A : Une Cible (Anneaux concentriques)
    concept_A = torch.exp(-(R - 6.0)**2 / 0.5) + torch.exp(-(R - 2.0)**2 / 0.5)
    psi_A = torch.sqrt(concept_A)

    # Concept B : Une Croix (Symétrie orthogonale)
    concept_B = torch.exp(-cerveau.X**2 / 1.0) * torch.exp(-(cerveau.Y/5)**2) + \
                torch.exp(-cerveau.Y**2 / 1.0) * torch.exp(-(cerveau.X/5)**2)
    psi_B = torch.sqrt(concept_B)

    # 1. Apprentissage simultané
    print("Étape 1 : Le fluide encode la Cible ET la Croix dans le même espace...")
    cerveau.add_memory(psi_A)
    cerveau.add_memory(psi_B)

    # 2. Traumatisme et Stimulus partiel
    # On donne au fluide JUSTE le quart supérieur gauche de la Cible + Énormément de bruit
    print("Étape 2 : Présentation d'un fragment corrompu (Un quart de la Cible)...")
    psi_input = psi_A.clone().to(torch.complex64) # Convert psi_input to complex type
    psi_input[N_grid//2:, :] = 0.0 # Efface le bas
    psi_input[:, N_grid//2:] = 0.0 # Efface la droite
    bruit = (torch.randn((N_grid, N_grid)) + 1j * torch.randn((N_grid, N_grid))) * 0.4
    psi_input += bruit
    rho_input = torch.abs(psi_input)**2

    # 3. Réflexion (Rappel)
    print("Étape 3 : Résolution de conflit par dynamique fluide...")
    psi_recalled = psi_input.clone()
    for t in range(250):
        psi_recalled = cerveau(psi_recalled)

    rho_recalled = torch.abs(psi_recalled)**2

    # ==========================================
    # Visualisation de la Discrimination
    # ==========================================
    fig, axes = plt.subplots(1, 4, figsize=(20, 5))
    fig.suptitle(r"AGI Aetherium : Superposition et Discrimination Holographique", fontsize=18, fontweight='bold')

    # A. Les concepts originaux fusionnés pour l'affichage
    axes[0].imshow((torch.abs(psi_A)**2 + torch.abs(psi_B)**2).numpy(), cmap='magma', origin='lower')
    axes[0].set_title("Concepts Originaux (A + B)")
    axes[0].axis('off')

    # B. La Mémoire Gravitationnelle totale (Un vrai réseau de Hopfield)
    axes[1].imshow(cerveau.phi_memory.cpu().numpy(), cmap='cividis', origin='lower')
    axes[1].set_title(r"Mémoire Latente (La Gravité $\Phi$)")
    axes[1].axis('off')

    # C. L'Entrée Corrompue
    axes[2].imshow(rho_input.cpu().numpy(), cmap='magma', origin='lower')
    axes[2].set_title("Stimulus : Quart de cible + Chaos")
    axes[2].axis('off')

    # D. Le Résultat
    axes[3].imshow(rho_recalled.cpu().numpy(), cmap='magma', origin='lower')
    axes[3].set_title("Résolution du Conflit (Rêve)")
    axes[3].axis('off')

    plt.tight_layout()
    plt.savefig('aetherium_agi_advanced.png', dpi=150)
    print("Discrimination terminée ! Résultat dans 'aetherium_agi_advanced.png'")