# -*- coding: utf-8 -*-
"""AGI Aetherium Complexe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rv9XiuQF1t7F9NTYe8cV_BI-i5RZP3Ce
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

# ============================================================
# 1. CONFIGURATION UNIFIÉE (TRL 6 - Niveau Complexe)
# ============================================================
class AetheriumComplexConfig:
    def __init__(self):
        # Vision et Perception
        self.in_channels = 1
        self.base_channels = 16
        self.spatial_size = 32

        # Tenseurs Aetherium
        self.dim_tensor = 32

        # Paramètres de Lensing GW (Validation Math 3 & 4)
        self.beta_0 = 0.02          # Couplage gravitationnel de base
        self.k_coupling = 0.5       # Sensibilité macro à la micro-cohérence
        self.k0_lensing = 1.0       # Constante d'intégration (c, G)

        # Hyperparamètres Physiques (Collatz & Riemann)
        self.k_blocks_collatz = 4
        self.collatz_epsilon = 1e-4

        # Poids des pertes
        self.w_rec = 1.0
        self.w_action = 0.1
        self.w_collatz = 0.1
        self.w_riemann = 0.05

        self.device = "cuda" if torch.cuda.is_available() else "cpu"

# ============================================================
# 2. OBSERVATEUR PHYSIQUE (Extraction des Métriques de Phase)
# ============================================================
class GWLensingObserver(nn.Module):
    """
    Extrait les métriques physiques falsifiables (C, beta_eff, DeltaPhi_GW)
    directement depuis l'espace latent (la pensée de l'AGI).
    """
    def __init__(self, cfg: AetheriumComplexConfig):
        super().__init__()
        self.cfg = cfg

    def forward(self, psi_latent: torch.Tensor):
        # psi_latent shape: (Batch, Time, Dim, 2)
        real, imag = psi_latent[..., 0], psi_latent[..., 1]

        # 1. Extraction de la Densité Quantique (rho) et Phase (theta)
        density = real**2 + imag**2
        phase = torch.atan2(imag, real)

        # 2. Calcul de la Cohérence C (Validation Math 2)
        # Basé sur la variance spatiale de la phase
        phase_variance = torch.var(phase, dim=-1, keepdim=True)
        C = torch.exp(-phase_variance) # (Batch, Time, 1)

        # 3. Calcul du Couplage Effectif beta_eff (Validation Math 3)
        beta_eff = self.cfg.beta_0 * (1 + self.cfg.k_coupling * C)

        # 4. Calcul de la Phase GW DeltaPhi(theta) (Validation Math 4)
        # Ici, la dimension latente agit comme notre espace d'intégration (ligne de visée).
        # On simule l'intégration de rho(l) dl en moyennant l'énergie latente.
        density_integral = density.mean(dim=-1, keepdim=True)

        # DeltaPhi_GW = k0 * beta_eff * integral(rho)
        delta_phi_gw = self.cfg.k0_lensing * beta_eff * density_integral

        return C, beta_eff, delta_phi_gw

# ============================================================
# 3. LE NOYAU FLUIDE TENSORIEL (Rappel de la V2)
# ============================================================
class RelativisticFluidCell(nn.Module):
    def __init__(self, cfg: AetheriumComplexConfig):
        super().__init__()
        self.cfg = cfg
        input_dim = 1 + cfg.dim_tensor * 3

        self.evolve_psi = nn.Sequential(
            nn.Linear(input_dim, cfg.dim_tensor * 2), nn.LayerNorm(cfg.dim_tensor * 2), nn.GELU()
        )
        self.evolve_omega = nn.Sequential(
            nn.Linear(input_dim, cfg.dim_tensor), nn.LayerNorm(cfg.dim_tensor), nn.Tanh()
        )

    def forward(self, phi, psi, omega):
        B = phi.shape[0]
        psi_flat = psi.view(B, -1)
        state_cat = torch.cat([phi, psi_flat, omega], dim=-1)

        # Évolution Quantique
        next_psi = (psi_flat + self.evolve_psi(state_cat)).view(B, self.cfg.dim_tensor, 2)

        # Dynamique Topologique (Vorticité)
        delta_omega = self.evolve_omega(state_cat)
        next_omega = omega + delta_omega

        # Équilibre de Bianchi
        real_curr, imag_curr = psi[..., 0], psi[..., 1]
        real_next, imag_next = next_psi[..., 0], next_psi[..., 1]

        density_current = (real_curr**2 + imag_curr**2).mean(dim=-1, keepdim=True)
        density_next = (real_next**2 + imag_next**2).mean(dim=-1, keepdim=True)

        phase_curr = torch.atan2(imag_curr, real_curr)
        C_curr = torch.exp(-torch.var(phase_curr, dim=-1, keepdim=True))
        beta_eff = self.cfg.beta_0 * (1 + self.cfg.k_coupling * C_curr)

        delta_phi = - (beta_eff * (density_next - density_current)) - (0.1 * delta_omega.mean(dim=-1, keepdim=True))
        next_phi = phi + delta_phi

        return next_phi, next_psi, next_omega

# (L'encodeur et le décodeur restent identiques à la version précédente pour condenser le code)
class SensoryEncoder(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(cfg.in_channels, cfg.base_channels, kernel_size=(5, 3), padding=(2, 1)), nn.GELU(),
            nn.Conv2d(cfg.base_channels, cfg.base_channels * 2, 4, 2, 1), nn.GELU(),
            nn.Conv2d(cfg.base_channels * 2, cfg.base_channels * 2, 4, 2, 1), nn.GELU(),
        )
        self.flat_size = (cfg.spatial_size // 4) ** 2 * (cfg.base_channels * 2)
        self.to_phi = nn.Linear(self.flat_size, 1)
        self.to_psi = nn.Linear(self.flat_size, cfg.dim_tensor * 2)
        self.to_omega = nn.Linear(self.flat_size, cfg.dim_tensor)

    def forward(self, x):
        feat = self.net(x).view(x.shape[0], -1)
        return self.to_phi(feat), self.to_psi(feat), self.to_omega(feat)

class CognitiveDecoder(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.cfg = cfg
        self.flat_size = (cfg.spatial_size // 4) ** 2 * (cfg.base_channels * 2)
        self.to_feat = nn.Sequential(nn.Linear(1 + cfg.dim_tensor * 3, self.flat_size), nn.GELU())
        self.net = nn.Sequential(
            nn.ConvTranspose2d(cfg.base_channels * 2, cfg.base_channels, 4, 2, 1), nn.GELU(),
            nn.ConvTranspose2d(cfg.base_channels, cfg.in_channels, 4, 2, 1), nn.Sigmoid()
        )

    def forward(self, phi, psi, omega):
        B = phi.shape[0]
        state_cat = torch.cat([phi, psi.view(B, -1), omega], dim=-1)
        feat = self.to_feat(state_cat).view(B, self.cfg.base_channels * 2, self.cfg.spatial_size // 4, self.cfg.spatial_size // 4)
        return self.net(feat)

class AetheriumAGI(nn.Module):
    def __init__(self, cfg: AetheriumComplexConfig):
        super().__init__()
        self.cfg = cfg
        self.encoder = SensoryEncoder(cfg)
        self.fluid_cell = RelativisticFluidCell(cfg)
        self.decoder = CognitiveDecoder(cfg)
        self.observer = GWLensingObserver(cfg) # Ajout de l'observateur métrique

    def forward(self, x_seq: torch.Tensor, steps_to_predict: int):
        B, T_in, C, H, W = x_seq.shape
        phi, psi, omega = None, None, None
        phi_h, psi_h, omega_h, preds = [], [], [], []

        # Burn-in
        for t in range(T_in):
            p, ps_flat, o = self.encoder(x_seq[:, t])
            ps = ps_flat.view(B, self.cfg.dim_tensor, 2)
            if phi is None: phi, psi, omega = p, ps, o
            else:
                phi, psi, omega = phi + p*0.1, psi + ps*0.1, omega + o*0.1
                phi, psi, omega = self.fluid_cell(phi, psi, omega)
            phi_h.append(phi); psi_h.append(psi); omega_h.append(omega)

        # Imagination
        for step in range(steps_to_predict):
            phi, psi, omega = self.fluid_cell(phi, psi, omega)
            preds.append(self.decoder(phi, psi, omega))
            phi_h.append(phi); psi_h.append(psi); omega_h.append(omega)

        psi_history = torch.stack(psi_h, dim=1)

        # Extraction des Métriques Falsifiables
        C_metric, beta_eff_metric, delta_phi_gw = self.observer(psi_history)

        return (torch.stack(preds, dim=1), torch.stack(phi_h, dim=1),
                psi_history, torch.stack(omega_h, dim=1),
                C_metric, beta_eff_metric, delta_phi_gw)

# ============================================================
# 4. DATASET COMPLEXE (Le Double Vortex en Orbite)
# ============================================================
class DoubleVortexOrbitDataset(Dataset):
    """
    Génère deux masses (baryons/vortex) orbitant l'une autour de l'autre.
    Cela oblige l'IA à apprendre le moment cinétique (Omega) et l'attraction mutuelle.
    """
    def __init__(self, num_samples=100, seq_len=12, size=32):
        self.num_samples = num_samples
        self.seq_len = seq_len
        self.size = size

    def __len__(self): return self.num_samples

    def __getitem__(self, idx):
        frames = torch.zeros(self.seq_len, 1, self.size, self.size)
        # Centre de masse
        cx, cy = self.size / 2, self.size / 2
        # Rayon de l'orbite et vitesse angulaire (aléatoire par vidéo)
        radius = np.random.uniform(5, 10)
        omega = np.random.uniform(0.2, 0.5)
        phase_init = np.random.uniform(0, 2 * math.pi)

        for t in range(self.seq_len):
            # Position du Vortex 1
            x1 = cx + radius * math.cos(omega * t + phase_init)
            y1 = cy + radius * math.sin(omega * t + phase_init)
            # Position du Vortex 2 (opposé)
            x2 = cx + radius * math.cos(omega * t + phase_init + math.pi)
            y2 = cy + radius * math.sin(omega * t + phase_init + math.pi)

            # Dessin des vortex (flous pour imiter des densités)
            ix1, iy1 = int(np.clip(x1, 1, self.size-2)), int(np.clip(y1, 1, self.size-2))
            ix2, iy2 = int(np.clip(x2, 1, self.size-2)), int(np.clip(y2, 1, self.size-2))

            frames[t, 0, ix1-1:ix1+2, iy1-1:iy1+2] = 0.8
            frames[t, 0, ix2-1:ix2+2, iy2-1:iy2+2] = 0.8
            # Cœur plus dense
            frames[t, 0, ix1, iy1] = 1.0
            frames[t, 0, ix2, iy2] = 1.0

        return frames

# ============================================================
# 5. PERTES PHYSIQUES (Rappel)
# ============================================================
def collatz_lyapunov_loss(psi_seq, k_blocks, epsilon):
    B, T, D, _ = psi_seq.shape
    if T <= k_blocks: return torch.tensor(0.0, device=psi_seq.device)
    loss = 0.0
    energy_seq = (psi_seq[..., 0]**2 + psi_seq[..., 1]**2).mean(dim=-1)
    for t in range(T - k_blocks):
        drift = energy_seq[:, t + k_blocks] - energy_seq[:, t]
        in_basin = (energy_seq[:, t] < 0.1).float()
        violation = F.relu(drift + epsilon) * (1.0 - in_basin)
        loss += violation.mean()
    return loss / (T - k_blocks)

def riemann_spectral_loss(psi_seq):
    primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
              59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131]
    log_p = torch.log(torch.tensor(primes, dtype=torch.float32, device=psi_seq.device))
    log_p = log_p / log_p.max()
    density = psi_seq[..., 0]**2 + psi_seq[..., 1]**2
    energy_spectrum = density.mean(dim=(0, 1))
    energy_sorted, _ = torch.sort(energy_spectrum, descending=False)
    energy_normalized = energy_sorted / (energy_sorted.max() + 1e-8)
    return F.mse_loss(energy_normalized, log_p)

# ============================================================
# 6. SCRIPT D'ENTRAÎNEMENT & EXTRACTION
# ============================================================
def train_complex_agi():
    cfg = AetheriumComplexConfig()
    model = AetheriumAGI(cfg).to(cfg.device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

    T_total, T_in = 12, 6
    T_pred = T_total - T_in

    dataset = DoubleVortexOrbitDataset(num_samples=250, seq_len=T_total, size=cfg.spatial_size)
    dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

    epochs = 12
    print(f"--- Démarrage AGI : Séquences Double Vortex (Orbite) ---")

    for epoch in range(epochs):
        model.train()
        total_loss, total_rec = 0, 0
        # Métriques moyennes pour le logging
        avg_C, avg_beta, avg_dphi = 0, 0, 0

        for batch in dataloader:
            batch = batch.to(cfg.device)
            optimizer.zero_grad()

            frames_in, frames_target = batch[:, :T_in], batch[:, T_in:]

            # Forward pass avec extraction des métriques
            preds, phi_h, psi_h, omega_h, C_m, beta_m, dphi_m = model(frames_in, steps_to_predict=T_pred)

            # Calcul des pertes
            l_rec = F.mse_loss(preds, frames_target)
            l_act = phi_h.pow(2).mean() + (psi_h[..., 0]**2 + psi_h[..., 1]**2).mean() + 0.25 * omega_h.pow(2).mean()
            l_col = collatz_lyapunov_loss(psi_h, cfg.k_blocks_collatz, cfg.collatz_epsilon)
            l_rie = riemann_spectral_loss(psi_h)

            loss = (cfg.w_rec * l_rec + cfg.w_action * l_act +
                    cfg.w_collatz * l_col + cfg.w_riemann * l_rie)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            total_loss += loss.item(); total_rec += l_rec.item()
            avg_C += C_m.mean().item()
            avg_beta += beta_m.mean().item()
            avg_dphi += dphi_m.mean().item()

        n_b = len(dataloader)
        print(f"Ep {epoch+1:02d} | Loss: {total_loss/n_b:.4f} | Rec: {total_rec/n_b:.4f} "
              f"|| Observables: C={avg_C/n_b:.4f}, β_eff={avg_beta/n_b:.4f}, Δφ_GW={avg_dphi/n_b:.4f}")

if __name__ == "__main__":
    train_complex_agi()